using System;

namespace SPCS.ApiModels.Ficha
{
    public class FichaResponseApiModel
    {
        public Guid Id { get; set; }
        public Guid PacienteId { get; set; }
        public DateTime DataCadastro { get; set; }
        public string MunicipioTrabalho { get; set; }
        public bool Gestante { get; set; }
        public bool Tabagismo { get; set; }
        public bool TabagismoAtual { get; set; }
        public bool TabagismoAnterior { get; private set; }
        public bool Etilismo { get; set; }
        public bool EtilismoAtual { get; set; }
        public bool EtilismoAnterior { get; set; }
        public bool IngestaoCafe { get; set; }
        public double CafeMlDia { get; set; }
        public string RelacaoTrabalho { get; set; }
        public string FuncaoTrabalho { get; set; }
        public bool ContatoPraguicida { get; set; }
        public string TempoContatoPraguicida { get; set; }
        public string FrequenciaContatoPraguicida { get; set; }
        public string UltimoContatoPraguicida { get; set; }
        public string FormaAplicacao { get; set; }
        public string ViaExposicao { get; set; }
        public bool Adoeceu { get; set; }
        public string QtdVezesAdoeceu { get; set; }
        public bool Internado { get; set; }
        public string QtdVezesInternado { get; set; }
        public string QuandoInterndo { get; set; }
        public string TipoContato { get; set; }
        public bool EquipamentoProtecao { get; set; }
        public bool RoupaProtecao { get; set; }
        public bool BotaProtecao { get; set; }
        public bool LuvasProtecao { get; set; }
        public bool MascaraProtecao { get; set; }
        public bool OculosProtecao { get; set; }
        public bool ProtetorAuricular { get; set; }
        public bool DoencaCardioVascular { get; set; }
        public bool HipertensaoArterial { get; set; }
        public bool HipotensaoArterial { get; set; }
        public bool Arritmia { get; set; }
        public bool AlteracaoSNervoso { get; set; }
        public bool DorCabeca { get; set; }
        public bool FraquezaMuscular { get; set; }
        public bool Tremedeira { get; set; }
        public bool TremorMuscular { get; set; }
        public bool VisãoTurvaEmbacada { get; set; }
        public bool AgitacaoIrritabilidade { get; set; }
        public bool VertigensTonturas { get; set; }
        public bool Formigamento { get; set; }
        public bool IncoordenacaoMotora { get; set; }
        public bool AparelhoDigestorio { get; set; }
        public bool ColicasDorBarriga { get; set; }
        public bool DorEstomago { get; set; }
        public bool AziaQueimacao { get; set; }
        public bool NauseasEnjoo { get; set; }
        public bool Vomito { get; set; }
        public bool Diarreia { get; set; }
        public bool AparelhoRespiratorio { get; set; }
        public bool FaltaDeAr { get; set; }
        public bool IrritaçaoNasal { get; set; }
        public bool CatarroEscarro { get; set; }
        public bool Tosse { get; set; }
        public bool AparelhoAuditivo { get; set; }
        public bool DiminuicaoAudicao { get; set; }
        public bool Zumbido { get; set; }
        public bool PeleMucosa { get; set; }
        public bool DcSensibilizante { get; set; }
        public bool DcIrritativa { get; set; }
        public bool IrritacaoOcular { get; set; }
        public bool AparelhoUrinario { get; set; }
        public bool DiminuicaoUrina { get; set; }
        public bool UrinaescuraSangue { get; set; }
        public bool Outro { get; set; }
        public string ExposicaoRaiox { get; set; }
        public int QuandodiasExposicao { get; set; }
        public bool TeveCancer { get; set; }
        public bool SncCancer { get; set; }
        public bool DigestorioCcancer { get; set; }
        public bool RespiratorioCancer { get; set; }
        public bool ReprodutorCancer { get; set; }
        public bool GlandularCancer { get; set; }
        public bool PeleOssoSangueCancer { get; set; }
        public bool FamiliaCancer { get; set; }
        public bool SNCCancerFamilia { get; set; }
        public bool DigestorioCancerfamilia { get; set; }
        public bool RespiratorioCancerfamilia { get; set; }
        public bool ReprodutorCancerfamilia { get; set; }
        public bool GlandularCancerfamilia { get; set; }
        public bool PeleOssoSangueCancerfamilia { get; set; }
        public bool EdaRegiao { get; set; }
        public double Ch_t { get; set; }
        public double Ch_e { get; set; }
        public double Ch_p { get; set; }
        public double Ast { get; set; }
        public double Alt { get; set; }
        public double Y_gt { get; set; }
        public double Creatinina { get; set; }
        public string Ambulatorio { get; set; }
        public double HabitoAlimentar { get; set; }
        public double Imc { get; set; }
        public int CircunferenciaAbdominal { get; set; }
        public bool DificuldadeEngravidar { get; set; }
        public bool AbortoEspontaneo { get; set; }
        public bool TemFilhos { get; set; }
        public bool FilhoMaFormacao { get; set; }
        public bool MedicamentoContinuo { get; set; }
        public string Medicamento { get; set; }
        public bool RemedioMicose { get; set; }
        public string NomeRemedio { get; set; }
    }
}
